Fix.

diff --git a/hooks/gradle/pre-commit b/hooks/gradle/pre-commit
--- a/hooks/gradle/pre-commit
+++ b/hooks/gradle/pre-commit
@@ -1,9 +1,9 @@
 #!/bin/sh
 gradle test
-if [$? = 0]
+if [ "$?" = "0" ]
 then
 	exit 0
 fi
 
-echo "I can't push. There are test failures!"
+echo "I can't commit. There are test failures!"
 exit 1
